### ISSUE TITLE
Update Snapchat

### ISSUE THREAD

**Issue by stevene1919** [2factorauth/passkeys#29]
### Site name

Snapchat

### Site URL

https://snapchat.com

### Update reason

Other (please describe below).

### Additional information

Snapchat is still rolling out passkey and isn't currently available everywhere (tested Australia).

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/passkeys/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/passkeys/pulls)

**Comment by fletcherdodd** [comment]
Hi @stevene1919,
Thanks for raising the request for this one to be added. I have actually added this one to our [Passkey directory](https://passkeys.2fa.directory/) via [this PR](https://github.com/2factorauth/passkeys/pull/15). I'll close this one off now.
