### ISSUE TITLE
Update British Airways

### ISSUE THREAD

**Issue by pmcarrion** [2factorauth/passkeys#33]
### Site name

British Airways

### Site URL

https://www.ba.com

### Update reason

It now supports passkey authentication.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/passkeys/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/passkeys/pulls)

**Comment by Carlgo11** [comment]
Thanks for the pull request @pmcarrion!
I see that you haven't added any documentation link. Could you find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, please attach screenshots of the 2FA setup and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

**Comment by Carlgo11** [comment]
So it is Qatar or Finnair that offer Passkey support?

**Comment by Carlgo11** [comment]
Resolved in 2factorauth/twofactorauth#8230
